/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pemadam.monitoring.view.pengguna;

import com.pemadam.monitoring.controller.PenggunaController;
import com.pemadam.monitoring.model.PenggunaModel;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuriko
 */
public class Pengguna extends javax.swing.JPanel {

    /**
     * Creates new form Pengguna
     */
    
    private int selectedId = -1;
    java.awt.Frame parent = (java.awt.Frame)
    javax.swing.SwingUtilities.getWindowAncestor(this);
    public Pengguna() {
        initComponents();
        tblPengguna.setModel(new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Nama", "Username", "No Telp", "Role"
            }
        ));
        tblPengguna.setRowHeight(25);
        tblPengguna.getColumnModel().getColumn(0).setPreferredWidth(10);  // ID
        tblPengguna.getColumnModel().getColumn(1).setPreferredWidth(150); // Nama
        tblPengguna.getColumnModel().getColumn(2).setPreferredWidth(150); // Username
        tblPengguna.getColumnModel().getColumn(3).setPreferredWidth(120); // No Telp
        tblPengguna.getColumnModel().getColumn(4).setPreferredWidth(100); // Role
        
        
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        tblPengguna.getColumnModel().getColumn(0).setCellRenderer(center); // ID
        tblPengguna.getColumnModel().getColumn(4).setCellRenderer(center); // Role

        
        tblPengguna.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                int row = tblPengguna.getSelectedRow();

                if (row == -1) {
                    selectedId = -1;
                } else {
                    selectedId = Integer.parseInt(
                        tblPengguna.getValueAt(row, 0).toString()
                    );
                }
            }
        });
        loadData();   
    }

    
    
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tblPengguna.getModel();
        model.setRowCount(0);

        PenggunaController controller = new PenggunaController();
        List<PenggunaModel> list = controller.getAllPengguna();

        for (PenggunaModel p : list) {
            model.addRow(new Object[]{
                p.getIdPengguna(),
                p.getNamaPengguna(),
                p.getUsername(),
                p.getNoTelp(),
                p.getRole()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengguna = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setText("Form Pengguna");

        tblPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenggunaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPenggunaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPengguna);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit))
                    .addComponent(jLabel2)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        TambahPenggunaDialog dialog =
        new TambahPenggunaDialog(parent, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(parent, "Pilih data dulu!");
            return;
        }
        PenggunaController controller = new PenggunaController();
        PenggunaModel p = controller.getPenggunaById(selectedId);
        DetailPenggunaDialog dialog = new DetailPenggunaDialog(parent, true);

        dialog.setData(
            p.getIdPengguna(),
            p.getNamaPengguna(),
            p.getUsername(),
            p.getNoTelp(),
            p.getRole()
        );

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        loadData(); 
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenggunaMouseClicked
       
        int row = tblPengguna.getSelectedRow();

        if (row != -1) {
            selectedId = Integer.parseInt(tblPengguna.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_tblPenggunaMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
         if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(parent, "Pilih data dulu!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            parent,
            "Yakin mau hapus data ini?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            PenggunaController controller = new PenggunaController();
            boolean sukses = controller.deletePengguna(selectedId);

            if (sukses) {
                javax.swing.JOptionPane.showMessageDialog(parent, "Data berhasil dihapus!");
                loadData();   
                selectedId = -1;
            } else {
                javax.swing.JOptionPane.showMessageDialog(parent, "Gagal hapus data!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblPenggunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenggunaMousePressed
        
        int row = tblPengguna.rowAtPoint(evt.getPoint());

        if (row == -1) {
            tblPengguna.clearSelection(); 
            selectedId = -1;         
        }
    }//GEN-LAST:event_tblPenggunaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPengguna;
    // End of variables declaration//GEN-END:variables
}
