/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pemadam.monitoring.view.log;

import com.pemadam.monitoring.controller.LogAktivitasController;
import com.pemadam.monitoring.model.LogAktivitasModel;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuriko
 */
public class LogAktivitas extends javax.swing.JPanel {

    /**
     * Creates new form LogAktivitas
     */
    
    
    java.awt.Frame parent = (java.awt.Frame)
    javax.swing.SwingUtilities.getWindowAncestor(this);
    public LogAktivitas() {
        initComponents();
        tblLog.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                "ID","ID Pengguna", "Waktu", "Aksi", "Tabel Terkait", "Record id", "Deskripsi"
            }
        ));
        
//        tblLog.getColumnModel().getColumn(0).setMinWidth(0);
//        tblLog.getColumnModel().getColumn(0).setMaxWidth(0);
//        tblLog.getColumnModel().getColumn(0).setWidth(0);

        tblLog.setRowHeight(25);
        tblLog.getColumnModel().getColumn(0).setPreferredWidth(10);  
        tblLog.getColumnModel().getColumn(1).setPreferredWidth(20); 
        tblLog.getColumnModel().getColumn(2).setPreferredWidth(100); 
        tblLog.getColumnModel().getColumn(3).setPreferredWidth(50); 
        tblLog.getColumnModel().getColumn(4).setPreferredWidth(50); 
        tblLog.getColumnModel().getColumn(5).setPreferredWidth(50); 
        tblLog.getColumnModel().getColumn(6).setPreferredWidth(200); 

        
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        
        tblLog.getColumnModel().getColumn(0).setCellRenderer(center); 
        tblLog.getColumnModel().getColumn(1).setCellRenderer(center); 
        tblLog.getColumnModel().getColumn(3).setCellRenderer(center); 
        tblLog.getColumnModel().getColumn(4).setCellRenderer(center);
        tblLog.getColumnModel().getColumn(5).setCellRenderer(center); 

        
        
        loadData();   
    }

    
    
    private void loadData() {

        DefaultTableModel model = (DefaultTableModel) tblLog.getModel();
        model.setRowCount(0);

        LogAktivitasController controller = new LogAktivitasController();
        List<LogAktivitasModel> list = controller.getLog();

        int no = 1;

        for (LogAktivitasModel a : list) {
            model.addRow(new Object[]{
        a.getIdLog(),             
        a.getIdPengguna(),
        a.getWaktu(),
        a.getAksi(),  
        a.getTabelTerkait(),
        a.getRecordId(),
        a.getDeskripsi()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLog = new javax.swing.JTable();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(1020, 570));
        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setText("Form Log Aktivitas");

        tblLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLogMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLogMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2)
                .addGap(62, 593, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLogMouseClicked
       
    }//GEN-LAST:event_tblLogMouseClicked

    private void tblLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLogMousePressed
        
    }//GEN-LAST:event_tblLogMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLog;
    // End of variables declaration//GEN-END:variables
}
