/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pemadam.monitoring.view.alat;

import com.pemadam.monitoring.controller.AlatController;
import com.pemadam.monitoring.model.AlatModel;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuriko
 */
public class DaftarAlat extends javax.swing.JPanel {

    /**
     * Creates new form Alat
     */
    
    private int selectedId = -1;
    private AlatController controller =  new AlatController();
    java.awt.Frame parent = (java.awt.Frame)
    javax.swing.SwingUtilities.getWindowAncestor(this);
    public DaftarAlat() {
        initComponents();
        tblAlat.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                "ID","No","Kode Alat", "Nama Alat", "Jenis", "Tanggal Pembelian", "Lokasi"
            }
        ));
        
        tblAlat.getColumnModel().getColumn(0).setMinWidth(0);
        tblAlat.getColumnModel().getColumn(0).setMaxWidth(0);
        tblAlat.getColumnModel().getColumn(0).setWidth(0);

        tblAlat.setRowHeight(25);
        tblAlat.getColumnModel().getColumn(1).setPreferredWidth(10);  // No
        tblAlat.getColumnModel().getColumn(2).setPreferredWidth(150); // Kode Alat
        tblAlat.getColumnModel().getColumn(3).setPreferredWidth(150); // Nama Alat
        tblAlat.getColumnModel().getColumn(4).setPreferredWidth(120); // Jenis
        tblAlat.getColumnModel().getColumn(5).setPreferredWidth(100); // Tanggal Pembelian
        tblAlat.getColumnModel().getColumn(5).setPreferredWidth(100); // Lokasi

        
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        tblAlat.getColumnModel().getColumn(1).setCellRenderer(center); // ID
        tblAlat.getColumnModel().getColumn(4).setCellRenderer(center); // Jenis

        
        tblAlat.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                int row = tblAlat.getSelectedRow();

                if (row == -1) {
                    selectedId = -1;
                } else {
                    selectedId = Integer.parseInt(
                        tblAlat.getValueAt(row, 0).toString()
                    );
                }
            }
        });
        loadData();   
    }

    
    
    private void loadData() {

        DefaultTableModel model = (DefaultTableModel) tblAlat.getModel();
        model.setRowCount(0);

        AlatController controller = new AlatController();
        List<AlatModel> list = controller.getAllAlat();

        int no = 1;

        for (AlatModel a : list) {
            model.addRow(new Object[]{
        a.getIdAlat(),
                no++,              
        a.getKodeAlat(),
        a.getNamaAlat(),
        a.getJenisAlat(),  
        a.getTglPembelian(),
        a.getNamaLokasi()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlat = new javax.swing.JTable();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(1020, 570));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(232, 31, 71));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/icons8-tools-32.png"))); // NOI18N
        jLabel2.setText(" Form Alat");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(503, 503, 503)
                .addComponent(btnAdd)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(6, 6, 6)
                                .addComponent(btnEdit)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tblAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAlatMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        TambahAlat dialog =
        new TambahAlat(parent, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlatMouseClicked
       
        int row = tblAlat.getSelectedRow();

        if (row != -1) {
            selectedId = Integer.parseInt(tblAlat.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_tblAlatMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
         if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(parent, "Pilih data dulu!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            parent,
            "Yakin mau hapus data ini?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            
            boolean sukses = controller.deleteAlat(selectedId);

            if (sukses) {
                javax.swing.JOptionPane.showMessageDialog(parent, "Data berhasil dihapus!");
                loadData();   
                selectedId = -1;
            } else {
                javax.swing.JOptionPane.showMessageDialog(parent, "Gagal hapus data!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblAlatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlatMousePressed
        
        int row = tblAlat.rowAtPoint(evt.getPoint());

        if (row == -1) {
            tblAlat.clearSelection(); 
            selectedId = -1;         
        }
    }//GEN-LAST:event_tblAlatMousePressed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(parent, "Pilih data dulu!");
            return;
        }
        AlatModel a = controller.getAlatById(selectedId);
        DetailAlat dialog = new DetailAlat(parent, true);

        dialog.setData(
            a.getIdAlat(),
            a.getKodeAlat(),
            a.getNamaAlat(),
            a.getJenisAlat(),
            a.getTglPembelian(),
            a.getIdLokasi()
        );

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        loadData();
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlat;
    // End of variables declaration//GEN-END:variables
}
