/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pemadam.monitoring.view.lokasi;

import com.pemadam.monitoring.controller.LokasiController;
import com.pemadam.monitoring.model.LokasiModel;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yuriko
 */
public class Lokasi extends javax.swing.JPanel {

    /**
     * Creates new form Lokasi
     */
    
    private int selectedId = -1;
    private LokasiController controller = new LokasiController();
    java.awt.Frame parent = (java.awt.Frame)
    javax.swing.SwingUtilities.getWindowAncestor(this);
    public Lokasi() {
        initComponents();
        tblLokasi.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                "ID","No","Nama Lokasi","Lantai", "Gedung"
            }
        ));
        
        tblLokasi.getColumnModel().getColumn(0).setMinWidth(0);
        tblLokasi.getColumnModel().getColumn(0).setMaxWidth(0);
        tblLokasi.getColumnModel().getColumn(0).setWidth(0);
        
        tblLokasi.setRowHeight(25);
        tblLokasi.getColumnModel().getColumn(1).setPreferredWidth(10);  // No
        tblLokasi.getColumnModel().getColumn(2).setPreferredWidth(150); // Nama Lokasi
        tblLokasi.getColumnModel().getColumn(3).setPreferredWidth(150); // Lantai
        tblLokasi.getColumnModel().getColumn(4).setPreferredWidth(120); // Gedung
        
        
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);

        tblLokasi.getColumnModel().getColumn(1).setCellRenderer(center); // No
        tblLokasi.getColumnModel().getColumn(3).setCellRenderer(center); // Lantai
        tblLokasi.getColumnModel().getColumn(4).setCellRenderer(center); // Gedung

        
        tblLokasi.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                int row = tblLokasi.getSelectedRow();

                if (row == -1) {
                    selectedId = -1;
                } else {
                    selectedId = Integer.parseInt(
                        tblLokasi.getValueAt(row, 0).toString()
                    );
                }
            }
        });
        loadData();   
    }

    
    
    private void loadData() {

        DefaultTableModel model = (DefaultTableModel) tblLokasi.getModel();
        model.setRowCount(0);

        LokasiController controller = new LokasiController();
        List<LokasiModel> list = controller.getAll();

        int no = 1;

        for (LokasiModel a : list) {
            model.addRow(new Object[]{
                a.getIdLokasi(),
                no++,              
                a.getNamaLokasi(),
                a.getLantai(),
                a.getGedung(),
                "Detail"
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLokasi = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(1022, 570));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(232, 31, 71));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/icons8-location-32.png"))); // NOI18N
        jLabel2.setText("Form Lokasi");

        tblLokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLokasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLokasiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLokasiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLokasi);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 554, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        TambahLokasiAlatDialog dialog =
        new TambahLokasiAlatDialog(parent, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(parent, "Pilih data dulu!");
            return;
        }
        LokasiModel a = controller.getLokasiById(selectedId);
        DetailLokasiAlatDialog dialog = new DetailLokasiAlatDialog(parent, true);

        dialog.setData(a);

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        loadData(); 
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblLokasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLokasiMouseClicked
       
        int row = tblLokasi.getSelectedRow();

        if (row != -1) {
            selectedId = Integer.parseInt(tblLokasi.getValueAt(row, 0).toString());
        }
    }//GEN-LAST:event_tblLokasiMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
         if (selectedId == -1) {
            javax.swing.JOptionPane.showMessageDialog(parent, "Pilih data dulu!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            parent,
            "Yakin mau hapus data ini?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            LokasiController controller = new LokasiController();
            boolean sukses = controller.deleteLokasi(selectedId);

            if (sukses) {
                javax.swing.JOptionPane.showMessageDialog(parent, "Data berhasil dihapus!");
                loadData();   
                selectedId = -1;
            } else {
                javax.swing.JOptionPane.showMessageDialog(parent, "Gagal hapus data!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblLokasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLokasiMousePressed
        
        int row = tblLokasi.rowAtPoint(evt.getPoint());

        if (row == -1) {
            tblLokasi.clearSelection(); 
            selectedId = -1;         
        }
    }//GEN-LAST:event_tblLokasiMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLokasi;
    // End of variables declaration//GEN-END:variables
}
