/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pemadam.monitoring.view.maintenance;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author zy
 */
public class Maintenance extends javax.swing.JPanel {
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Maintenance.class.getName());

    /**
     * Creates new form Maintenance
     */
    public Maintenance() {
        initComponents();
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Pilih Alat");
        model.addColumn("Data Inspeksi");
        model.addColumn("Kode Alat");
        model.addColumn("Nama Alat");
        model.addColumn("Jenis Alat");
        model.addColumn("Lokasi");
        model.addColumn("Tanggal Beli");
        
        tmaintenance.setModel(model);
        
        cmb.addItem("APAR");
        cmb.addItem("APAB");
        cmb.addItem("HYDRANT");
        cmb.addItem("SPRINKLER");
        cmb.addItem("SUPPRESSION");
        cmb.addItem("Manifold");
        cmb.addItem("PENDUKUNG");
        cmb.addItem("PROTEKSI");
        
        cmbx1.addItem("Baik");
        cmbx1.addItem("Rusak Ringan");
        cmbx1.addItem("Rusak Berat");
        
        cmbx3.addItem("Gudang");
        cmbx3.addItem("Lab");
        cmbx3.addItem("Kantor");
        
        DefaultTableModel model = new DefaultTableModel(
        new String []{
            "Pilih Alat",
            "Data Inspeksi",
            "Kode Alat",
            "Nama Alat",
            "Jenis Alat",
            "Lokasi",
            "Tanggal Beli"
        },0);
        
       tmaintenance.setModel(model);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        badd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbx1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtkolat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnamlat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbx2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbx3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmaintenance = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Maintenance ");

        badd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        badd.setText("Add");
        badd.addActionListener(this::baddActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(" Plih Alat :");

        cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih Alat" }));
        cmb.addActionListener(this::cmbActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Pilih Data Inspeksi :");

        cmbx1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Data Inspeksi", "Baik", "Rusak Ringan", "Rusak Berat" }));
        cmbx1.addActionListener(this::cmbx1ActionPerformed);

        jLabel3.setText("Kode Alat");

        jLabel4.setText("Nama Alat");

        jLabel6.setText("Jenis Alat");

        cmbx2.setFocusCycleRoot(true);

        jLabel7.setText("Lokasi");

        cmbx3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gudang", "Lab", "Kantor" }));

        jLabel8.setText("Tanggal Beli");

        tmaintenance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tmaintenance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(cmbx1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbx2, 0, 151, Short.MAX_VALUE)
                                .addComponent(txtnamlat)
                                .addComponent(txtkolat)
                                .addComponent(cmbx3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtkolat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnamlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cmbx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cmbx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbActionPerformed

    private void cmbx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbx1ActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        // TODO add your handling code here:
        if(txtkolat.getText().isEmpty() ||
           txtnamlat.getText().isEmpty()){
            Component This;
            JOptionPane.showMessageDialog(This,"Data belum lengkap");
            
            return;
        }
        String alat = cmb.getSelectedItem().toString();
        String inspeksi = cmbx1.getSelectedItem().toString();
        String kode = txtkolat.getText();
        String nama = txtnamlat.getText();
        String jenis = cmbx2.getSelectedItem().toString();
        String lokasi = cmbx3.getSelectedItem().toString();
        
        String tanggal = "";
        
        if(jDateChooser1.getDate() != null){
           SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            tanggal = sdf.format(jDateChooser1.getDate());
        }
        
        DefaultTableModel model = (DefaultTableModel)tmaintenance.getModel();
        
        model.addrow(new Object[]{
        alat,
        inspeksi,
        kode,
        nama,
        jenis,
        lokasi,
        tanggal
        });
    }//GEN-LAST:event_baddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JComboBox<String> cmbx1;
    private javax.swing.JComboBox<String> cmbx2;
    private javax.swing.JComboBox<String> cmbx3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tmaintenance;
    private javax.swing.JTextField txtkolat;
    private javax.swing.JTextField txtnamlat;
    // End of variables declaration//GEN-END:variables
}
